window.MOONIE_ASANAS={
 breath:{name:'Respiración consciente',cat:'Llegada',instruction:'Siéntate o túmbate cómodamente. Observa el aire entrar y salir sin forzar el ritmo.',breath:'Inhala suave y deja que la exhalación se alargue de forma natural.',transition:'Abre poco a poco los ojos y lleva movimiento al cuerpo.'},
 child:{name:'Balasana · Niño',cat:'Descanso',instruction:'Desde cuadrupedia, lleva la cadera hacia los talones y deja descansar el torso. Separa las rodillas si resulta más cómodo.',breath:'Respira hacia la espalda y las costillas.',transition:'Deslízate hacia cuadrupedia con calma.'},
 catcow:{name:'Gato–Vaca',cat:'Movilidad',instruction:'En cuatro apoyos, mueve la columna con la respiración. Inhala abriendo el pecho y exhala redondeando la espalda.',breath:'Inhala al abrir; exhala al redondear.',transition:'Regresa a una columna neutra.'},
 table:{name:'Cuadrupedia',cat:'Base',instruction:'Manos bajo hombros, rodillas bajo caderas y columna larga. Empuja suavemente el suelo.',breath:'Respiración estable.',transition:'Prepara perro boca abajo o la siguiente movilidad.'},
 down:{name:'Adho Mukha Svanasana · Perro boca abajo',cat:'Fuerza suave',instruction:'Eleva las caderas formando una V. Flexiona las rodillas cuanto necesites para conservar la espalda larga.',breath:'Inhala al alargar; exhala al relajar hombros.',transition:'Camina hacia las manos.'},
 forward:{name:'Uttanasana · Pinza de pie',cat:'Flexión',instruction:'Flexiona las rodillas y deja caer el torso. No busques tocar el suelo; busca longitud y relajación.',breath:'Exhala al soltar.',transition:'Flexiona rodillas y sube lentamente.'},
 half:{name:'Ardha Uttanasana · Media pinza',cat:'Movilidad',instruction:'Alarga la espalda desde la coronilla hasta el coxis. Manos en muslos o espinillas.',breath:'Inhala al crear longitud.',transition:'Exhala y vuelve a la pinza.'},
 mountain:{name:'Tadasana · Montaña',cat:'Base',instruction:'De pie, pies firmes, rodillas suaves, pelvis neutra y coronilla hacia arriba. Relaja mandíbula y hombros.',breath:'Respira amplio y estable.',transition:'Desde aquí inicia el movimiento.'},
 lowlunge:{name:'Anjaneyasana · Zancada baja',cat:'Caderas',instruction:'Un pie delante y rodilla trasera apoyada. Mantén el torso erguido y la pelvis cómoda.',breath:'Inhala creando espacio; exhala suavizando la pelvis.',transition:'Apoya las manos para volver a cuadrupedia.'},
 halfsplit:{name:'Ardha Hanumanasana · Media apertura',cat:'Piernas',instruction:'Desde la zancada, lleva la cadera atrás y alarga la pierna delantera sin bloquear la rodilla.',breath:'Inhala alargar; exhala suavemente.',transition:'Dobla la rodilla y vuelve a la zancada.'},
 sphinx:{name:'Esfinge',cat:'Espalda',instruction:'Boca abajo, antebrazos apoyados y pecho abierto. Alarga la columna antes de elevar el esternón.',breath:'Inhala expandiendo el pecho.',transition:'Baja y descansa.'},
 cobra:{name:'Bhujangasana · Cobra suave',cat:'Espalda',instruction:'Eleva el pecho usando la espalda. No necesitas estirar los brazos ni subir mucho.',breath:'Inhala al elevar; exhala al bajar.',transition:'Baja y vuelve a Niño.'},
 locust:{name:'Salabhasana · Langosta',cat:'Espalda',instruction:'Activa piernas y espalda para elevar suavemente pecho y/o piernas. Mantén el cuello largo.',breath:'Inhala al elevar; exhala al bajar.',transition:'Descansa boca abajo.'},
 bridge:{name:'Setu Bandha · Puente',cat:'Caderas',instruction:'Boca arriba, pies cerca de los glúteos. Presiona los pies y eleva la pelvis sin cargar el cuello.',breath:'Inhala al elevar; exhala estabilizando.',transition:'Baja vértebra a vértebra.'},
 butterfly:{name:'Baddha Konasana · Mariposa',cat:'Caderas',instruction:'Une las plantas de los pies y deja caer las rodillas sin empujarlas. Usa soportes si quieres.',breath:'Respira hacia abdomen y pelvis.',transition:'Cierra las piernas lentamente.'},
 wide:{name:'Upavistha Konasana · Apertura sentada',cat:'Piernas',instruction:'Abre las piernas hasta una distancia cómoda. Alarga la columna y solo después inclínate.',breath:'Inhala para alargar; exhala para suavizar.',transition:'Vuelve al centro con las manos.'},
 seated:{name:'Paschimottanasana · Pinza sentada',cat:'Piernas',instruction:'Piernas extendidas o flexionadas. Alarga la espalda antes de inclinarte desde las caderas.',breath:'Inhala alargar; exhala soltar.',transition:'Regresa lentamente a sentado.'},
 staff:{name:'Dandasana · Bastón',cat:'Base',instruction:'Piernas extendidas, manos junto a las caderas y columna erguida. Flexiona rodillas si lo necesitas.',breath:'Respiración estable.',transition:'Dobla las rodillas para la siguiente postura.'},
 hero:{name:'Virasana · Héroe',cat:'Descanso',instruction:'Siéntate entre los talones o sobre un soporte. No fuerces las rodillas.',breath:'Respira hacia el abdomen.',transition:'Apoya las manos para salir.'},
 easy:{name:'Sukhasana · Postura cómoda',cat:'Meditación',instruction:'Siéntate con la pelvis elevada si lo necesitas. Alarga la columna sin rigidez.',breath:'Respiración natural.',transition:'Lleva la atención al cuerpo.'},
 wall:{name:'Viparita Karani · Piernas en la pared',cat:'Restaurativa',instruction:'Descansa las piernas en una pared y permite que el peso del cuerpo se vuelva pesado.',breath:'Exhala largo.',transition:'Dobla las rodillas y gira de lado para salir.'},
 happy:{name:'Ananda Balasana · Bebé feliz',cat:'Caderas',instruction:'Sujeta pies o muslos y deja que las rodillas se acerquen hacia las axilas sin tirar.',breath:'Respira hacia la pelvis.',transition:'Suelta y abraza las rodillas.'},
 figure4:{name:'Figura 4 tumbada',cat:'Glúteos',instruction:'Cruza un tobillo sobre el muslo contrario y acerca las piernas hacia ti manteniendo el sacro pesado.',breath:'Exhala y relaja la cadera.',transition:'Suelta lentamente y cambia de lado.'},
 pigeon:{name:'Paloma suave',cat:'Caderas',instruction:'Lleva una pierna delante y la otra atrás. Usa un soporte bajo la cadera si hace falta.',breath:'Respira sin buscar profundidad.',transition:'Vuelve a cuadrupedia y cambia de lado.'},
 warrior:{name:'Virabhadrasana II · Guerrero II',cat:'Fuerza',instruction:'Base amplia, rodilla delantera sobre el tobillo y brazos largos. Mantén la pelvis estable.',breath:'Respira amplio.',transition:'Estira la pierna y vuelve al centro.'},
 triangle:{name:'Trikonasana · Triángulo',cat:'Lateral',instruction:'Desde una base amplia, alarga un costado y desciende solo hasta conservar espacio en la cintura.',breath:'Inhala abriendo; exhala al alargar.',transition:'Presiona los pies y vuelve al centro.'},
 tree:{name:'Vrksasana · Árbol',cat:'Equilibrio',instruction:'Apoya el pie libre en tobillo, pantorrilla o muslo, nunca directamente sobre la rodilla. Fija la mirada.',breath:'Respira estable.',transition:'Baja el pie con control.'},
 chair:{name:'Utkatasana · Silla',cat:'Fuerza',instruction:'Lleva la cadera atrás como si fueras a sentarte. Mantén el peso repartido y el pecho abierto.',breath:'Inhala al alargar; exhala al estabilizar.',transition:'Estira las piernas y vuelve a Montaña.'},
 crescent:{name:'Zancada alta',cat:'Fuerza',instruction:'Desde una zancada estable, eleva el torso y los brazos. Mantén la pelvis orientada hacia delante.',breath:'Respira amplio.',transition:'Baja las manos y vuelve a Perro.'},
 twist:{name:'Torsión sentada',cat:'Torsión',instruction:'Siéntate estable y gira desde la parte alta de la espalda. Crece al inhalar y gira al exhalar.',breath:'Inhala al crecer; exhala al girar.',transition:'Vuelve al centro lentamente.'},
 supinetwist:{name:'Torsión tumbada',cat:'Torsión',instruction:'Boca arriba, lleva las rodillas hacia un lado manteniendo los hombros pesados.',breath:'Exhala al dejar caer las piernas.',transition:'Vuelve al centro y cambia de lado.'},
 knees:{name:'Rodillas al pecho',cat:'Descanso',instruction:'Abraza las rodillas y permite que la zona lumbar se relaje.',breath:'Respira hacia el abdomen.',transition:'Suelta las piernas.'},
 fish:{name:'Pez suave',cat:'Apertura',instruction:'Apoya espalda y antebrazos o utiliza un cojín. El objetivo es abrir el pecho sin forzar el cuello.',breath:'Respira hacia el pecho.',transition:'Sal con mucho cuidado.'},
 corpse:{name:'Savasana · Relajación final',cat:'Cierre',instruction:'Túmbate cómodamente y deja que el suelo sostenga todo tu peso. No necesitas hacer nada más.',breath:'Respiración natural.',transition:'Mueve dedos, gira de lado y siéntate lentamente.'},
 meditation:{name:'Meditación sentada',cat:'Cierre',instruction:'Observa la respiración y las sensaciones del cuerpo. Si aparece un pensamiento, vuelve con suavidad.',breath:'No cambies la respiración; simplemente obsérvala.',transition:'Frota las manos y abre los ojos.'}
};
const sequences=[
['Despertar Suave','Hatha suave','principiante',25,'movilidad y presencia',['breath','child','catcow','table','down','forward','half','mountain','lowlunge','halfsplit','seated','supinetwist','corpse'],['con-energia','flexible','en-calma']],
['Columna Despierta','Movilidad','principiante',30,'movilidad de columna',['breath','child','catcow','table','down','sphinx','cobra','child','twist','supinetwist','knees','corpse'],['flexible','liberada','en-calma']],
['Caderas Libres','Yin','principiante',35,'caderas y pelvis',['breath','child','catcow','down','lowlunge','halfsplit','butterfly','figure4','pigeon','happy','supinetwist','corpse'],['flexible','liberada','relajada']],
['Espalda Suave','Yin restaurativo','principiante',30,'espalda y pecho',['breath','child','catcow','sphinx','cobra','child','bridge','supinetwist','knees','fish','corpse'],['relajada','liberada','en-calma']],
['Mañana Luminosa','Hatha','intermedio',35,'energía y cuerpo completo',['breath','catcow','down','forward','half','mountain','chair','crescent','warrior','triangle','tree','forward','corpse'],['con-energia','fuerte','concentrada']],
['Hombros y Cuello','Restaurativo','principiante',25,'cuello, hombros y respiración',['breath','easy','catcow','child','sphinx','fish','twist','wall','corpse'],['relajada','en-calma','conectada']],
['Piernas Ligeras','Hatha suave','principiante',30,'piernas y movilidad',['breath','catcow','down','forward','lowlunge','halfsplit','warrior','triangle','happy','wall','corpse'],['flexible','con-energia','relajada']],
['Anochecer','Yin','principiante',35,'bajar revoluciones',['breath','child','catcow','down','lowlunge','butterfly','figure4','seated','supinetwist','wall','corpse','meditation'],['dormir','relajada','en-calma']],
['Columna Lunar','Yin','principiante',40,'columna y sistema nervioso',['breath','child','catcow','sphinx','child','twist','butterfly','supinetwist','knees','wall','corpse','meditation'],['en-calma','liberada','conectada']],
['Raíces','Hatha + equilibrio','intermedio',35,'estabilidad y enraizamiento',['breath','mountain','chair','warrior','triangle','tree','lowlunge','crescent','child','seated','corpse'],['equilibrio','fuerte','concentrada']]
];
const arch=[
['Calma Profunda','Yin restaurativo','principiante',40,'sistema nervioso y descanso',['breath','child','catcow','butterfly','figure4','seated','supinetwist','wall','corpse','meditation'],['relajada','en-calma','dormir']],
['Sueño Profundo','Yin','principiante',45,'preparación para dormir',['breath','child','catcow','down','lowlunge','butterfly','figure4','happy','supinetwist','wall','corpse','meditation'],['dormir','relajada','en-calma']],
['Caderas y Emociones','Yin','principiante',40,'caderas y liberación de tensión',['breath','child','catcow','lowlunge','halfsplit','butterfly','pigeon','figure4','supinetwist','corpse'],['liberada','flexible','conectada']],
['Corazón Abierto','Hatha suave','principiante',35,'pecho y respiración',['breath','catcow','sphinx','cobra','child','bridge','fish','supinetwist','corpse'],['conectada','liberada','en-calma']],
['Espalda Sin Tensión','Yin restaurativo','principiante',35,'espalda y movilidad',['breath','child','catcow','sphinx','cobra','child','twist','knees','supinetwist','corpse'],['liberada','relajada','flexible']],
['Fuerza Serena','Hatha','intermedio',40,'fuerza consciente',['breath','catcow','down','forward','half','mountain','chair','warrior','crescent','triangle','tree','child','corpse'],['fuerte','con-energia','concentrada']],
['Equilibrio Lunar','Hatha suave','intermedio',35,'equilibrio y concentración',['breath','mountain','chair','warrior','triangle','tree','lowlunge','crescent','child','twist','corpse'],['equilibrio','concentrada','conectada']],
['Movilidad Total','Hatha movilidad','principiante',35,'movilidad global',['breath','catcow','down','forward','half','lowlunge','halfsplit','warrior','triangle','butterfly','corpse'],['flexible','con-energia','liberada']],
['Ritual de Luna','Yin + meditación','principiante',45,'introspección',['breath','easy','child','catcow','butterfly','pigeon','seated','twist','wall','corpse','meditation'],['conectada','en-calma','dormir']],
['Desbloqueo de Caderas','Yin','principiante',40,'caderas y glúteos',['breath','catcow','down','lowlunge','halfsplit','figure4','pigeon','happy','supinetwist','corpse'],['liberada','flexible','relajada']]
];
const names=['Esencia','Fluir','Suave','Profunda','Nocturna'];
window.MOONIE_ROUTINES=[];let num=1;
for(const x of sequences){window.MOONIE_ROUTINES.push(make(num++,x));}
for(const x of arch){for(let v=0;v<5;v++){if(num>60)break;let y=[...x];let seq=[...x[5]];if(v===1)seq=seq.slice();if(v===2)seq=['breath',...seq.filter((s,i)=>!(i===0&&s==='breath'))];if(v===3&&seq.includes('cobra'))seq.splice(seq.indexOf('cobra')+1,0,'child');if(v===4&&!seq.includes('meditation'))seq.push('meditation');y[0]=x[0]+' · '+names[v];y[3]=x[3]+[0,5,-5,5,10][v];y[5]=seq;window.MOONIE_ROUTINES.push(make(num++,y));}}
function make(n,x){return{id:'r'+String(n).padStart(2,'0'),number:n,name:x[0],style:x[1],level:x[2],duration:x[3],focus:x[4],feelings:x[6],poses:x[5],description:'Práctica estructurada con llegada, calentamiento, trabajo principal, compensación y relajación final. Cada postura prepara la siguiente para que la secuencia tenga sentido.'}}
